excerpt_separator: "<!--more-->"
pygments: true
url: http://justinkelly.github.io
title: Justin Kelly
tagline: various ramblings
description: My awesome new site
permalink: /:title
paginate: 5

# Build settings
# markdown: kramdown
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks
