title: Justin Kelly
tagline: various ramblings
description: Justin Kelly - various ramblings
url: https://blog.justin.kelly.org.au
enforce_ssl: https://blog.justin.kelly.org.au
permalink: /:title/
excerpt_separator: <!--more-->
paginate: 10

gems:
   - jekyll-paginate
   - jekyll-gist

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

prose:
  siteurl: 'http://blog.justin.kelly.org.au/'
  media: 'assets/images'
  ignore:
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
