excerpt_separator: "\n\n"
pygments: true
markdown: kramdown
url: http://justinkelly.github.io
title: Justin Kelly
tagline: various ramblings
description: My awesome new site
permalink: /:title
paginate: 5
