excerpt_separator: "<!--more-->"
pygments: true
url: http://justinkelly.github.io
title: Justin Kelly
tagline: various ramblings
description: My awesome new site
permalink: /:title
paginate: 5

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

# Build settings
#markdown: redcarpet

#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks","lax_spacing","no_intra_emphasis"]
