title: Justin Kelly
tagline: various ramblings
description: Justin Kelly - various ramblings
url: https://blog.justin.kelly.org.au
enforce_ssl: https://blog.justin.kelly.org.au
permalink: /:title/
excerpt_separator: <!--more-->
paginate: 10

# Owner/author
owner:
  name:           Justin Kelly
  avatar:         jk.png
  email:          justin@kelly.org.au
  description:    Web Developer | Business Analytics | Library Technology based in Melbourne, Australia
  # Social networking links used in footer
  twitter:        _justin_kelly
  facebook:       justin.kelly.org.au
  github:         justinkelly
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/u/0/+JustinKelly0
  
gems:
   - jekyll-paginate
   - jekyll-gist
   - jekyll-srcset

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
srcset:
  optipng: true
  cache: "img/cache/"

prose:
  siteurl: 'http://blog.justin.kelly.org.au/'
  media: 'img'
  ignore:
    - /_layouts
    - /_includes
    - /.gitignore
    - /.travis.yml
    - /Gemfile
    - /atom.xml
    - /tags
    - /CNAME
    - /admin
  metadata:
    _posts:
      - name: "excerpt_separator"
        field:
          element: "hidden"
          value: "<!--more-->"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "comments"
        field:
          label: "Comments"
          element: "checkbox"
          value: "true"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Add Tags"
          alterable: true
