excerpt_separator: "<!--more-->"
pygments: true
url: http://justinkelly.github.io
title: Justin Kelly
tagline: various ramblings
description: My awesome new site
permalink: /:title
paginate: 5

#markdown: kramdown
#kramdown:
#  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
