title: Justin Kelly
tagline: Justin Kelly
description: Justin Kelly
url: https://justin.kelly.org.au
enforce_ssl: https://justin.kelly.org.au
permalink: /:title/
excerpt_separator: <!--more-->
timezone: Australia/Melbourne

# Owner/author
owner:
  name:           Justin Kelly
  avatar:         jk.png
  email:          justin@kelly.org.au
  description:    Web Developer, Business Analytics, Data Engineer specialising in PHP and Tableau
  # Social networking links used in footer
  twitter:        _justin_kelly
  facebook:       justin.kelly.org.au
  github:         justinkelly
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/u/0/+JustinKelly0
  
plugins: [ jekyll-gist, jekyll-srcset, jekyll-minifier, jekyll-sitemap, jekyll-feed]

markdown: kramdown

include: 
   - "_headers"
   - "_redirects"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
srcset:
  optipng: true
  cache: "img/cache/"

# reCaptcha
reCaptcha:
    siteKey: "6LeMoygUAAAAAEo97WDnpKdmp1jLdgQ6aIG41gs0"
    secret: "edDZoWzS/wjuiP4fnRZDU7OQXLrUN5HbNVG5tJ/VJ8Xp+xsY6xM44+i2z/4fHKIvfnVD3ZheobZx0+gOFptxBwYnAj6SqwHgNOUpGyFBZYBFKGDfcwHBD8i6gmP7fOrCwQ7FmbVrRuWIpHIJbqCYXM2BM4IjQbx0rZB09WB4QcU="

sass:
    sass_dir: _sass
    style: compressed

prose:
  siteurl: 'https://justin.kelly.org.au/'
  media: 'img'
  ignore:
    - /_layouts
    - /_includes
    - /.gitignore
    - /.travis.yml
    - /Gemfile
    - /atom.xml
    - /tags
    - /CNAME
    - /admin
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "Title goes here"
      - name: "comments"
        field:
          label: "Comments"
          element: "checkbox"
          value: true
      - name: "tags"
        field:
          element: "textarea"
          label: "Tags"
          value: ''


# Staticman comments
staticmanUrl: https://staticman-justinkelly.herokuapp.com/v3/entry/github/justinkelly/justinkelly.github.io/master/comments

jekyll-minifier:
  exclude: '*.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob pattern
  preserve_php: false               # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: false               # Default: true
  compress_javascript: true         # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
