title: Justin Kelly
tagline: various ramblings
description: Justin Kelly - various ramblings
url: http://justinkelly.github.io
permalink: /:title
#excerpt_separator: "<!--more-->"
paginate: 10

gems: [jekyll-paginate]

markdown: kramdown
kramdown:
  input: GFM 
  
  
  
