excerpt_separator: "<!--more-->"
pygments: true
url: http://justinkelly.github.io
title: Justin Kelly
tagline: various ramblings
description: My awesome new site
permalink: /:title
paginate: 10

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

# Build settings
#markdown: redcarpet

#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks","lax_spacing","no_intra_emphasis"]

prose:
  rooturl: '_posts'
  siteurl: 'http://blog.justin.kelly.org.au'
  media: 'public/images'
  metadata:
    _posts:
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
     
