title: Justin Kelly
tagline: various ramblings
description: Justin Kelly - various ramblings
url: https://blog.justin.kelly.org.au
enforce_ssl: https://blog.justin.kelly.org.au
permalink: /:title/
excerpt_separator: <!--more-->
paginate: 10
timezone: Australia/Melbourne

# Owner/author
owner:
  name:           Justin Kelly
  avatar:         jk.png
  email:          justin@kelly.org.au
  description:    Web Developer | Business Analytics | Library Technology based in Melbourne, Australia
  # Social networking links used in footer
  twitter:        _justin_kelly
  facebook:       justin.kelly.org.au
  github:         justinkelly
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/u/0/+JustinKelly0
  
gems:
   - jekyll-paginate
   - jekyll-gist
   - jekyll-srcset

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
srcset:
  optipng: true
  cache: "img/cache/"

# reCaptcha
reCaptcha:
    siteKey: "6LeMoygUAAAAAEo97WDnpKdmp1jLdgQ6aIG41gs0"
    secret: "edDZoWzS/wjuiP4fnRZDU7OQXLrUN5HbNVG5tJ/VJ8Xp+xsY6xM44+i2z/4fHKIvfnVD3ZheobZx0+gOFptxBwYnAj6SqwHgNOUpGyFBZYBFKGDfcwHBD8i6gmP7fOrCwQ7FmbVrRuWIpHIJbqCYXM2BM4IjQbx0rZB09WB4QcU="

prose:
  siteurl: 'https://blog.justin.kelly.org.au/'
  media: 'img'
  ignore:
    - /_layouts
    - /_includes
    - /.gitignore
    - /.travis.yml
    - /Gemfile
    - /atom.xml
    - /tags
    - /CNAME
    - /admin
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "Title goes here"
      - name: "comments"
        field:
          label: "Comments"
          element: "checkbox"
          value: true
      - name: "tags"
        field:
          element: "textarea"
          label: "Tags"
          value: ''

# Staticman comments
staticmanUrl: https://api.staticman.net/v2/entry/justinkelly/justinkelly.github.io/master/comments
