title: Justin Kelly
tagline: various ramblings
description: Justin Kelly - various ramblings
url: http://justinkelly.github.io
permalink: /:title
#excerpt_separator: "<!--more-->"
paginate: 10

markdown: kramdown
kramdown:
  input: GFM 

 gems:
   - jekyll-paginate
